### ISSUE TITLE
Oyente crashes on certain contract, Segfault

### ISSUE THREAD

**Issue by D-Nice** [melonproject/oyente#115]
Using the docker container, oyente crashes via a segmentation fault, while trying to do the concurrency bug check it seems. Oddly, the same contract can be checked via the oyente browser-solidity/remix webpage, however, it returns a different result on the callstack attack, indicating true on the web one, and false on the one I tried with docker.

Here's the command along with the remote contract:

```
python oyente.py -ru https://raw.githubusercontent.com/oraclize/ethereum-api/master/connectors/oraclizeConnector.sol
```

greeter check worked fine

**Comment by inian** [comment]
Hey, this seems to be z3 crashing because of the maximum recursive depth being reached. Can you run it with the depth limit (dl) command line option? 

```
python oyente.py -ru https://raw.githubusercontent.com/oraclize/ethereum-api/master/connectors/oraclizeConnector.sol -dl 50
```

This segfault doesnt seem to be caught by our normal error handling though. Must be because it happens in the C-code of z3 and its python bindings don't propogate the error properly upwards.

**Comment by D-Nice** [comment]
I can confirm with the dl option it worked. However, there was still some z3 trace printed. Also, as mentioned previously, the analysis from the container, results in a different one to that of the one here: http://oyente.melonport.com/
Namely being that the latter indicates a callstack attack being possible.
