### ISSUE TITLE
Container EVM Version Warning

### ISSUE THREAD

**Issue by fang19911030** [melonproject/oyente#386]
I tried oyente container, I found every report includes the warning about evm version like this:
**WARNING:root:You are using evm version 1.8.2. The supported version is 1.7.3**
I think I shouldn't get this warning because I am using the container. Second, I am wondering if this version issue will affect the analysis of oyente?

**Comment by yxliang01** [comment]
Hey, may I know which docker image you are using (i.e. whether using existing downloaded one, or you built yourself)? The version mismatch might lead to Oyente crash(changed interface), etc... It's hard to say without looking deeply into the updates between version.

**Comment by fang19911030** [comment]
The image tag is latest. I used the command in the Readme.
`docker pull luongnguyen/oyente && docker run -i -t luongnguyen/oyente`

**Comment by yxliang01** [comment]
I see. Sorry that the image is actually outdated. I've scheduled to push to docker hub, but haven't managed to do so due to covid-19. For now, maybe you want to try building from the latest dockerfile if you would like to use supported evm, or install the supported evm manually in based on that image.

**Comment by yxliang01** [comment]
@fang19911030 Do you still have the issue? If not, maybe we can close this issue.
